Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "newaccount"
  config.ssh.insert_key = true
  config.ssh.forward_agent = true
  # Nginx port
  config.vm.network :forwarded_port, guest: 80, host: 8060
  # Tomcat port
  config.vm.network :forwarded_port, guest: 8080, host: 8061

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
  end

  # web part
  config.vm.synced_folder "../", "/var/www"
  config.vm.synced_folder "../task-executor/web", "/expanded-war"

  $script = <<SCRIPT
	if [ ! -f /vagrant/.updated ]; then
    	apt-get update
    	apt-get upgrade -y
		touch /vagrant/.updated
	fi

	# Install Nginx

	apt-get install -y nginx
	rm /etc/nginx/nginx.conf
	ln -s /vagrant/nginx.conf /etc/nginx/nginx.conf
	touch /var/www/index.html

	service stop nginx
	service start nginx

	# Install Oracle Java

	JDK=jdk-8u111-linux-x64.tar.gz
	JDIR=/opt/jdk1.8.0_111
	if [ ! -f /vagrant/$JDK ]; then
		wget -q -O /vagrant/$JDK --no-cookies --no-check-certificate --header "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie" "http://download.oracle.com/otn-pub/java/jdk/8u111-b14/jdk-8u111-linux-x64.tar.gz"
	fi 

	cd /opt
	if [ ! -d $JDIR ]; then
		tar -xzvf /vagrant/$JDK
	fi

	ln -s $JDIR/bin/java /usr/bin/java
	ln -s $JDIR/bin/javac /usr/bin/javac
	ln -s $JDIR/bin/jar /usr/bin/jar

	echo "export JAVA_HOME=$JDIR" >>/etc/environment

	# Install Camunda Tomcat distribution	

	if [ ! -f /vagrant/camunda-bpm-tomcat-7.5.0.tar.gz ]; then
		wget -q -O /vagrant/camunda-bpm-tomcat-7.5.0.tar.gz https://camunda.org/release/camunda-bpm/tomcat/7.5/camunda-bpm-tomcat-7.5.0.tar.gz
	fi

	mkdir -p /opt/camunda
	cd /opt/camunda
	if [ ! -d /opt/camunda/server ]; then
		tar -xzvf /vagrant/camunda-bpm-tomcat-7.5.0.tar.gz
	fi
	
	rm /etc/rc.local
	echo "export JAVA_HOME=$JDIR" >/etc/rc.local
	echo "cd /opt/camunda/server/apache-tomcat-8.0.24" >>/etc/rc.local
	echo "sudo -u vagrant /opt/camunda/server/apache-tomcat-8.0.24/bin/startup.sh" >>/etc/rc.local
	ln -s /expanded-war /opt/camunda/server/apache-tomcat-8.0.24/webapps/task-executor
	cp /vagrant/tomcat-users.xml /opt/camunda/server/apache-tomcat-8.0.24/conf/tomcat-users.xml
	chown vagrant /opt/camunda -R
	chmod a+x /etc/rc.local	
	service rc.local start
SCRIPT

  config.vm.provision "shell", inline: $script
end
